version: '3.8'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: plenademo
      MYSQL_USER: plenademo
      MYSQL_PASSWORD: plenademo
      MYSQL_ROOT_PASSWORD: plenademo
    network_mode: bridge
    volumes:
      - ./data:/var/lib/mysql